services:
    mongo:
      image: mongo:latest
      ports:
        - '27017:27017'
      volumes:
        - mongo-data:/data/db
      networks:
        - my_network

    backend:
      build:
        context: Todo-Api
        dockerfile: Dockerfile
      volumes:
        - ./Todo-Api:/app
      ports:
        - '5000:5000'
      environment:
        - JWT_SECRET=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.C0dPeB9pQiQrTeaSwEumidK0gvenpfIuEYwA3Fy29MA
      depends_on:
        - mongo
      networks:
        - my_network

    frontend:
      build:
        context: Todo-Web
      ports:
        - '3000:3000'
      depends_on:
        - backend
      environment:
        - API_URL=http://Todo-Api:5000

networks:
  my_network:
    driver: bridge

volumes:
  mongo-data: